-- ============================================
-- Schéma de base de données pour Gestion EPN
-- Migration depuis Access vers MySQL
-- Version 2 compatible, sans casser l'application existante
-- ============================================

CREATE DATABASE IF NOT EXISTS `epn_gestion` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `epn_gestion`;

-- ============================================
-- Table : INSCRIPTION (Usagers communs)
-- ============================================
CREATE TABLE IF NOT EXISTS `inscription` (
  `NUM_INSCRIPTION` INT(11) NOT NULL AUTO_INCREMENT,
  `DATE_INSCRIPTION` VARCHAR(255) DEFAULT NULL,
  `ESPACE` VARCHAR(255) DEFAULT NULL,
  `REFERENT` VARCHAR(255) DEFAULT NULL,
  `DATE_NAISSANCE` VARCHAR(255) DEFAULT NULL,
  `CIVILITE` VARCHAR(50) DEFAULT NULL,
  `NOMS_PRENOMS` VARCHAR(255) DEFAULT NULL,
  `ADRESSE` TEXT DEFAULT NULL,
  `CODE_VILLE` VARCHAR(10) DEFAULT NULL,
  `PAYS` VARCHAR(100) DEFAULT NULL,
  `TELEPHONES_PORTABLE` VARCHAR(50) DEFAULT NULL,
  `TELEPHONES_FIXE` VARCHAR(50) DEFAULT NULL,
  `SITUATION` VARCHAR(100) DEFAULT NULL,
  `EQUIPEMENT_PERSONNEL` VARCHAR(100) DEFAULT NULL,
  `CADRE_UTILISATION` VARCHAR(100) DEFAULT NULL,
  `PROFIL` VARCHAR(100) DEFAULT NULL,
  `EMAIL` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`NUM_INSCRIPTION`),
  KEY `idx_noms_prenoms` (`NOMS_PRENOMS`),
  KEY `idx_date_inscription` (`DATE_INSCRIPTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table : FREQUENTATION1 (Site BAC)
-- ============================================
CREATE TABLE IF NOT EXISTS `frequentation1` (
  `NUM_FREQUENTATION` INT(11) NOT NULL AUTO_INCREMENT,
  `DATE_FREQUENTATION` VARCHAR(255) DEFAULT NULL,
  `ESPACE_FREQUENTE` VARCHAR(255) DEFAULT NULL,
  `REFERENT` VARCHAR(255) DEFAULT NULL,
  `CIVILITE` VARCHAR(50) DEFAULT NULL,
  `NOMS_PRENOMS` VARCHAR(255) DEFAULT NULL,
  `POSTES` VARCHAR(50) DEFAULT NULL,
  `HEURE_ENTREE` VARCHAR(50) DEFAULT NULL,
  `HEURE_SORTIE` VARCHAR(50) DEFAULT NULL,
  `UTILISATIONS` VARCHAR(255) DEFAULT NULL,
  `CASQUE` VARCHAR(50) DEFAULT NULL,
  `WEBCAM` VARCHAR(50) DEFAULT NULL,
  `NOMBRE_COPIES` INT(11) DEFAULT NULL,
  `OBSERVATIONS` TEXT DEFAULT NULL,
  `TEST1` VARCHAR(50) DEFAULT NULL,
  `TEST2` VARCHAR(50) DEFAULT NULL,
  `TEST3` VARCHAR(50) DEFAULT NULL,
  `TEST4` VARCHAR(50) DEFAULT NULL,
  `TEST5` VARCHAR(50) DEFAULT NULL,
  `TEST6` VARCHAR(50) DEFAULT NULL,
  `TEST7` VARCHAR(50) DEFAULT NULL,
  `TEST8` VARCHAR(50) DEFAULT NULL,
  `TEST9` VARCHAR(50) DEFAULT NULL,
  `TEST10` VARCHAR(50) DEFAULT NULL,
  `TEST11` VARCHAR(50) DEFAULT NULL,
  `TEST12` VARCHAR(50) DEFAULT NULL,
  `TEST13` VARCHAR(50) DEFAULT NULL,
  `TEST14` VARCHAR(50) DEFAULT NULL,
  `TEST15` VARCHAR(50) DEFAULT NULL,
  `TEST16` VARCHAR(50) DEFAULT NULL,
  `TEST17` VARCHAR(50) DEFAULT NULL,
  `TEST18` VARCHAR(50) DEFAULT NULL,
  `TEST19` VARCHAR(50) DEFAULT NULL,
  `TEST20` VARCHAR(50) DEFAULT NULL,
  `ASSISTANCE` VARCHAR(50) DEFAULT NULL,
  `CODE_VILLE` VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`NUM_FREQUENTATION`),
  KEY `idx_date_frequentation` (`DATE_FREQUENTATION`),
  KEY `idx_noms_prenoms` (`NOMS_PRENOMS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table : FREQUENTATION2 (Site MAC)
-- ============================================
CREATE TABLE IF NOT EXISTS `frequentation2` (
  `NUM_FREQUENTATION` INT(11) NOT NULL AUTO_INCREMENT,
  `DATE_FREQUENTATION` VARCHAR(255) DEFAULT NULL,
  `ESPACE_FREQUENTE` VARCHAR(255) DEFAULT NULL,
  `REFERENT` VARCHAR(255) DEFAULT NULL,
  `CIVILITE` VARCHAR(50) DEFAULT NULL,
  `NOMS_PRENOMS` VARCHAR(255) DEFAULT NULL,
  `POSTES` VARCHAR(50) DEFAULT NULL,
  `HEURE_ENTREE` VARCHAR(50) DEFAULT NULL,
  `HEURE_SORTIE` VARCHAR(50) DEFAULT NULL,
  `UTILISATIONS` VARCHAR(255) DEFAULT NULL,
  `CASQUE` VARCHAR(50) DEFAULT NULL,
  `WEBCAM` VARCHAR(50) DEFAULT NULL,
  `NOMBRE_COPIES` INT(11) DEFAULT NULL,
  `OBSERVATIONS` TEXT DEFAULT NULL,
  `TEST1` VARCHAR(50) DEFAULT NULL,
  `TEST2` VARCHAR(50) DEFAULT NULL,
  `TEST3` VARCHAR(50) DEFAULT NULL,
  `TEST4` VARCHAR(50) DEFAULT NULL,
  `TEST5` VARCHAR(50) DEFAULT NULL,
  `TEST6` VARCHAR(50) DEFAULT NULL,
  `TEST7` VARCHAR(50) DEFAULT NULL,
  `TEST8` VARCHAR(50) DEFAULT NULL,
  `TEST9` VARCHAR(50) DEFAULT NULL,
  `TEST10` VARCHAR(50) DEFAULT NULL,
  `TEST11` VARCHAR(50) DEFAULT NULL,
  `TEST12` VARCHAR(50) DEFAULT NULL,
  `TEST13` VARCHAR(50) DEFAULT NULL,
  `TEST14` VARCHAR(50) DEFAULT NULL,
  `TEST15` VARCHAR(50) DEFAULT NULL,
  `TEST16` VARCHAR(50) DEFAULT NULL,
  `TEST17` VARCHAR(50) DEFAULT NULL,
  `TEST18` VARCHAR(50) DEFAULT NULL,
  `TEST19` VARCHAR(50) DEFAULT NULL,
  `TEST20` VARCHAR(50) DEFAULT NULL,
  `ASSISTANCE` VARCHAR(50) DEFAULT NULL,
  `CODE_VILLE` VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`NUM_FREQUENTATION`),
  KEY `idx_date_frequentation` (`DATE_FREQUENTATION`),
  KEY `idx_noms_prenoms` (`NOMS_PRENOMS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table : ATELIERS1 (Site BAC)
-- ============================================
CREATE TABLE IF NOT EXISTS `ateliers1` (
  `NUM_ATELIER` INT(11) NOT NULL AUTO_INCREMENT,
  `DATE_ATELIER` VARCHAR(255) DEFAULT NULL,
  `ESPACE_ATELIER` VARCHAR(255) DEFAULT NULL,
  `REFERENT` VARCHAR(255) DEFAULT NULL,
  `CIVILITE` VARCHAR(50) DEFAULT NULL,
  `NOMS_PRENOMS` VARCHAR(255) DEFAULT NULL,
  `TELEPHONES_PORTABLE` VARCHAR(50) DEFAULT NULL,
  `TELEPHONES_FIXE` VARCHAR(50) DEFAULT NULL,
  `ATELIER_CHOISI` VARCHAR(255) DEFAULT NULL,
  `PERIODE_ATELIER` VARCHAR(100) DEFAULT NULL,
  `SITUATION_FORMATION` VARCHAR(100) DEFAULT NULL,
  `OBSERVATIONS` TEXT DEFAULT NULL,
  `STATUT` VARCHAR(50) DEFAULT NULL,
  `FORMATEUR` VARCHAR(255) DEFAULT NULL,
  `CODE_VILLE` VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`NUM_ATELIER`),
  KEY `idx_date_atelier` (`DATE_ATELIER`),
  KEY `idx_noms_prenoms` (`NOMS_PRENOMS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table : ATELIERS2 (Site MAC)
-- ============================================
CREATE TABLE IF NOT EXISTS `ateliers2` (
  `NUM_ATELIER` INT(11) NOT NULL AUTO_INCREMENT,
  `DATE_ATELIER` VARCHAR(255) DEFAULT NULL,
  `ESPACE_ATELIER` VARCHAR(255) DEFAULT NULL,
  `REFERENT` VARCHAR(255) DEFAULT NULL,
  `CIVILITE` VARCHAR(50) DEFAULT NULL,
  `NOMS_PRENOMS` VARCHAR(255) DEFAULT NULL,
  `TELEPHONES_PORTABLE` VARCHAR(50) DEFAULT NULL,
  `TELEPHONES_FIXE` VARCHAR(50) DEFAULT NULL,
  `ATELIER_CHOISI` VARCHAR(255) DEFAULT NULL,
  `PERIODE_ATELIER` VARCHAR(100) DEFAULT NULL,
  `SITUATION_FORMATION` VARCHAR(100) DEFAULT NULL,
  `OBSERVATIONS` TEXT DEFAULT NULL,
  `STATUT` VARCHAR(50) DEFAULT NULL,
  `FORMATEUR` VARCHAR(255) DEFAULT NULL,
  `CODE_VILLE` VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`NUM_ATELIER`),
  KEY `idx_date_atelier` (`DATE_ATELIER`),
  KEY `idx_noms_prenoms` (`NOMS_PRENOMS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table : POSTES (Gestion des postes en temps réel)
-- ============================================
CREATE TABLE IF NOT EXISTS `postes` (
  `ID_POSTE` INT(11) NOT NULL AUTO_INCREMENT,
  `NUMERO_POSTE` INT(11) NOT NULL,
  `SITE` ENUM('BAC', 'MAC') NOT NULL,
  `NOMS_PRENOMS` VARCHAR(255) DEFAULT NULL,
  `UTILISATIONS` VARCHAR(255) DEFAULT NULL,
  `HEURE_DEBUT` TIME DEFAULT NULL,
  `HEURE_FIN` TIME DEFAULT NULL,
  `STATUT` ENUM('Libre', 'En cours', 'Terminé') DEFAULT 'Libre',
  `DATE_UTILISATION` DATE DEFAULT NULL,
  `DERNIERE_MAJ` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_POSTE`),
  UNIQUE KEY `unique_poste_site_date` (`NUMERO_POSTE`, `SITE`, `DATE_UTILISATION`),
  KEY `idx_site_date` (`SITE`, `DATE_UTILISATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table : AGENTS
-- ============================================
CREATE TABLE IF NOT EXISTS `agents` (
  `ID_AGENT` INT(11) NOT NULL AUTO_INCREMENT,
  `NOM_AGENT` VARCHAR(255) NOT NULL,
  `PRENOM_AGENT` VARCHAR(255) DEFAULT NULL,
  `ACTIF` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`ID_AGENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- V2 COMPATIBILITY LAYER (NON-BREAKING)
-- Prépare les futures pages de requêtes,
-- statistiques graphiques et exports CSV.
-- ============================================

CREATE TABLE IF NOT EXISTS `sites` (
  `CODE_SITE` ENUM('BAC', 'MAC') NOT NULL,
  `NOM_SITE` VARCHAR(100) NOT NULL,
  `LIBELLE_PUBLIC` VARCHAR(150) DEFAULT NULL,
  `ADRESSE_SITE` VARCHAR(255) DEFAULT NULL,
  `ACTIF` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`CODE_SITE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `sites` (`CODE_SITE`, `NOM_SITE`, `LIBELLE_PUBLIC`, `ADRESSE_SITE`, `ACTIF`) VALUES
  ('BAC', 'EPN SITE BAC', 'Cyber-Espace de Ducos', 'Chemin Tantan, 97224 Ducos, Martinique', 1),
  ('MAC', 'EPN SITE MAC', 'Cyber-Base de Ducos', '34 Rue Zizine et des Etages, 97224 Ducos, Martinique', 1)
ON DUPLICATE KEY UPDATE
  `NOM_SITE` = VALUES(`NOM_SITE`),
  `LIBELLE_PUBLIC` = VALUES(`LIBELLE_PUBLIC`),
  `ADRESSE_SITE` = VALUES(`ADRESSE_SITE`),
  `ACTIF` = VALUES(`ACTIF`);

DROP VIEW IF EXISTS `vue_inscriptions`;
CREATE VIEW `vue_inscriptions` AS
SELECT
  `NUM_INSCRIPTION` AS `ID_SOURCE`,
  `DATE_INSCRIPTION`,
  `ESPACE`,
  `REFERENT`,
  `DATE_NAISSANCE`,
  `CIVILITE`,
  `NOMS_PRENOMS`,
  `ADRESSE`,
  `CODE_VILLE`,
  `PAYS`,
  `TELEPHONES_PORTABLE`,
  `TELEPHONES_FIXE`,
  `SITUATION`,
  `EQUIPEMENT_PERSONNEL`,
  `CADRE_UTILISATION`,
  `PROFIL`,
  `EMAIL`
FROM `inscription`;

DROP VIEW IF EXISTS `vue_frequentations`;
CREATE VIEW `vue_frequentations` AS
SELECT
  'BAC' AS `SITE`,
  `NUM_FREQUENTATION` AS `ID_SOURCE`,
  `DATE_FREQUENTATION`,
  `ESPACE_FREQUENTE`,
  `REFERENT`,
  `CIVILITE`,
  `NOMS_PRENOMS`,
  `POSTES`,
  `HEURE_ENTREE`,
  `HEURE_SORTIE`,
  `UTILISATIONS`,
  `CASQUE`,
  `WEBCAM`,
  `NOMBRE_COPIES`,
  `OBSERVATIONS`,
  `ASSISTANCE`,
  `CODE_VILLE`
FROM `frequentation1`
UNION ALL
SELECT
  'MAC' AS `SITE`,
  `NUM_FREQUENTATION` AS `ID_SOURCE`,
  `DATE_FREQUENTATION`,
  `ESPACE_FREQUENTE`,
  `REFERENT`,
  `CIVILITE`,
  `NOMS_PRENOMS`,
  `POSTES`,
  `HEURE_ENTREE`,
  `HEURE_SORTIE`,
  `UTILISATIONS`,
  `CASQUE`,
  `WEBCAM`,
  `NOMBRE_COPIES`,
  `OBSERVATIONS`,
  `ASSISTANCE`,
  `CODE_VILLE`
FROM `frequentation2`;

DROP VIEW IF EXISTS `vue_ateliers`;
CREATE VIEW `vue_ateliers` AS
SELECT
  'BAC' AS `SITE`,
  `NUM_ATELIER` AS `ID_SOURCE`,
  `DATE_ATELIER`,
  `ESPACE_ATELIER`,
  `REFERENT`,
  `CIVILITE`,
  `NOMS_PRENOMS`,
  `TELEPHONES_PORTABLE`,
  `TELEPHONES_FIXE`,
  `ATELIER_CHOISI`,
  `PERIODE_ATELIER`,
  `SITUATION_FORMATION`,
  `OBSERVATIONS`,
  `STATUT`,
  `FORMATEUR`,
  `CODE_VILLE`
FROM `ateliers1`
UNION ALL
SELECT
  'MAC' AS `SITE`,
  `NUM_ATELIER` AS `ID_SOURCE`,
  `DATE_ATELIER`,
  `ESPACE_ATELIER`,
  `REFERENT`,
  `CIVILITE`,
  `NOMS_PRENOMS`,
  `TELEPHONES_PORTABLE`,
  `TELEPHONES_FIXE`,
  `ATELIER_CHOISI`,
  `PERIODE_ATELIER`,
  `SITUATION_FORMATION`,
  `OBSERVATIONS`,
  `STATUT`,
  `FORMATEUR`,
  `CODE_VILLE`
FROM `ateliers2`;

CREATE TABLE IF NOT EXISTS `exports_historique` (
  `ID_EXPORT` INT(11) NOT NULL AUTO_INCREMENT,
  `TYPE_EXPORT` ENUM('csv', 'requete', 'statistique') NOT NULL,
  `SITE` ENUM('BAC', 'MAC', 'GLOBAL') DEFAULT 'GLOBAL',
  `PERIODE_DEBUT` DATE DEFAULT NULL,
  `PERIODE_FIN` DATE DEFAULT NULL,
  `FORMAT_EXPORT` VARCHAR(50) DEFAULT 'csv',
  `FILTRES_JSON` LONGTEXT DEFAULT NULL,
  `DATE_CREATION` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_EXPORT`),
  KEY `idx_export_type_site` (`TYPE_EXPORT`, `SITE`),
  KEY `idx_export_dates` (`PERIODE_DEBUT`, `PERIODE_FIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

